include:
  - project: 'zeroseven/gitlab-ci-templates'
    ref: master
    file: '/typo3/zeroseven-extension.gitlab-ci.yml'

stages:
  - lint
  - build
  - release

php-cs-fixer:
  stage: lint
  image:
    name: oskarstark/php-cs-fixer-ga
    entrypoint: ["/bin/ash", "-c"]
  before_script:
    - ''
  script:
    - /usr/local/bin/php-cs-fixer --version
    - /usr/local/bin/php-cs-fixer fix --dry-run --using-cache no --diff
