services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Zeroseven\Semantilizer\:
    resource: '../Classes/*'

  dashboard.widget.checkHeadings:
    class: 'Zeroseven\Semantilizer\Widgets\CheckHeadings'
    arguments:
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'checkHeadings'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:z7_semantilizer/Resources/Private/Language/locallang.xlf:widget.title'
        description: 'LLL:EXT:z7_semantilizer/Resources/Private/Language/locallang.xlf:widget.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'small'
