services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Zeroseven\Semantilizer\:
    resource: '../Classes/*'

  dashboard.widget.faultyHeadings:
    class: 'Zeroseven\Semantilizer\Widgets\FaultyHeadingsWidget'
    arguments:
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'faultyHeadings'
        groupNames: 'systemInfo'
        title: 'faultyHeadings'
        description: 'LLL:EXT:widgets/Resources/Private/Language/locallang.xlf:widgets.dashboard.widget.statusReport.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'medium'
